### PR TITLE
change mod genuinetools/reg to vanilla

### PR DESCRIPTION
**Pull request by jabielecki**
Instead of using tomoyamachi's fork we can now use the vanilla upstream
package genuinetools/reg. This package gets better maintenance.

Also introducing new checksums for reg's children/dependecies.

Signed-off-by: Jakub Bielecki <jakub.bielecki@codilime.com>

### CODE REVIEW

**Comment by knqyf263** [comment]
@jabielecki Thank you! Would you apply `go mod tidy`?

**Comment by jabielecki** [comment]
With pleasure sir, `go mod tidy` there is. (Tested) @knqyf263

**Comment by jabielecki** [comment]
I like this project. I'll be contributing more this and next month :)

**Comment by knqyf263** [comment]
@jabielecki Thanks a lot!

**Pull request merged**
