### PR TITLE
add azure token auth

### PR DESCRIPTION
**Pull request by cgroschupp**

### CODE REVIEW

**Comment by knqyf263** [comment]
Thanks for the contribution! We prefer depending on well-maintained libraries. Can we implement it without [chrismellard/docker-credential-acr-env](https://github.com/chrismellard/docker-credential-acr-env)?

**Comment by cgroschupp** [comment]
@knqyf263 ok i removed the docker-credential-acr-env module. but now i need some help how to implement the test for my credentials store.

**Comment by knqyf263** [comment]
Thanks for the update.

**Comment by cgroschupp** [comment]
Test are added.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Merge this PR after updating Go to 1.17.
https://github.com/aquasecurity/fanal/pull/379

**Comment by knqyf263** [comment]
Thanks!

**Comment by cgroschupp** [comment]
@knqyf263 thank you for your support.

**Comment by knqyf263** [comment]
Note that this is not effective in Trivy until Trivy updates the version of fanal. If you want to support this capability, it would be appreciated if you open a pull request in Trivy.

**Pull request merged**
