### PR TITLE
feat(jar): allow setting Maven Central URL using environment variable

### PR DESCRIPTION
**Pull request by kobus-v-schoor**

### CODE REVIEW

**Comment by knqyf263** [comment]
https://github.com/aquasecurity/go-dep-parser/pull/90

**Comment by kobus-v-schoor** [comment]
Sorry it looks like I missed some or other dep, I pushed the fix

**Comment by knqyf263** [comment]
No, it is not your fault. We just need to bump up Go to 1.18.

**Comment by knqyf263** [comment]
We need to merge https://github.com/aquasecurity/fanal/pull/453 first.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks

**Pull request merged**
